name: Pytest

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install Test dependencies
      run: |
        pip install pytest lxml
    - name: Test with pytest
      run: |
        pytest -v